all:
	(cd timerLib && make install)
	(cd 2* && make)
	(cd 4* && make)
	(cd 11* && make)
	(cd runToy && make)

clean:
	(cd timerLib && make clean)
	(cd 2* && make clean)
	(cd 4* && make clean)
	(cd 11* && make clean)
	(cd runToy && make clean)
	rm -rf h lib
